import Link from 'next/link';

export const metadata = {
  title: 'Terms of Service - StrangerChat',
  description: 'Terms of Service agreements for StrangerChat platform.',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gray-50 pt-20">
      <div className="max-w-3xl mx-auto px-6 py-16 bg-white rounded-2xl shadow-sm border border-gray-100 mt-10 mb-20 text-gray-800">
        <h1 className="text-3xl font-black text-gray-900 mb-6">Terms of Service</h1>
        <p className="text-sm text-gray-500 mb-8">Last Updated: April 16, 2026</p>
        
        <div className="space-y-6 prose prose-blue max-w-none">
          <section>
            <h2 className="text-xl font-bold mt-8 mb-3">1. Acceptance of Terms</h2>
            <p className="text-gray-600 leading-relaxed">
              By accessing and using StrangerChat, you agree to comply with and be bound by these Terms of Service. If you do not agree to these terms, you must not use our platform.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold mt-8 mb-3">2. User Conduct</h2>
            <p className="text-gray-600 leading-relaxed">
              You must be at least 18 years old to use this service. You agree not to use the service for any unlawful purpose, to harass others, or to distribute malicious content.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold mt-8 mb-3">3. AI Moderation & Enforcement</h2>
            <p className="text-gray-600 leading-relaxed">
              StrangerChat utilizes AI moderation tools to monitor text and media. We reserve the right to instantly and permanently ban any IP address or user who violates our safety guidelines.
            </p>
          </section>

           <section>
            <h2 className="text-xl font-bold mt-8 mb-3">4. Limitation of Liability</h2>
            <p className="text-gray-600 leading-relaxed">
              StrangerChat provides the platform "as is". We are not responsible for the content generated by users during their anonymous chats.
            </p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-gray-100 text-center">
          <Link href="/" className="text-blue-600 font-medium hover:underline">
            ← Return to Home
          </Link>
        </div>
      </div>
    </div>
  );
}
